// BDD-style end-to-end coverage of the entire YANES UI.
//
// Every knob, preset, option, button, and config in the editor is exercised through a
// Given/When/Then scenario that drives real audio. The suite has four layers:
//
//   Unit        pure parameter-table self-tests (defaults, ranges, value-to-text, parse round-trip)
//   Integration per-parameter CLAP process() checks with real audio output
//   System      full E2E editor walks: page navigation, every preset, every widget gesture
//   Coverage    a coverage matrix printed at the end that fails if any control is untested
//
// The editor runs through ui_editor.hpp's C++ API; every parameter edit is also pushed
// through the real clap_plugin_params_t and rendered into audio buffers we measure.

#include "clap_harness.hpp"
#include "params.hpp"
#include "ui_editor.hpp"
#include "ui_layout.hpp"
#include "ui_pages.hpp"

#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstdarg>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <map>
#include <set>
#include <string>
#include <unordered_map>
#include <vector>

using namespace harness;
using namespace yanes::ui;
namespace P = yanes::params;

// ===========================================================================
//  BDD DSL
// ===========================================================================

namespace bdd {

struct Step { std::string verb, text; };

struct Scenario {
  std::string name;
  std::vector<Step> steps;
  bool failed = false;
  std::string failure;
  void begin(const std::string& n) { name = n; steps.clear(); failed = false; failure.clear(); }
  void add(const std::string& verb, const std::string& text) {
    steps.push_back({verb, text});
    std::printf("  | %-7s %s\n", verb.c_str(), text.c_str());
  }
  void fail(const std::string& msg) {
    if (!failed) { failed = true; failure = msg; std::printf("    FAIL: %s\n", msg.c_str()); }
  }
};

static Scenario* g_scenario = nullptr;
static int g_passed = 0;
static int g_failed = 0;

inline void scenario_add(const std::string& verb, const std::string& text) {
  g_scenario->add(verb, text);
}
inline void scenario_fail(const std::string& msg) {
  if (g_scenario) g_scenario->fail(msg);
  else std::fprintf(stderr, "FAIL (no scenario): %s\n", msg.c_str());
}

#define GIVEN(text) ::bdd::scenario_add("GIVEN", text)
#define WHEN(text)  ::bdd::scenario_add("WHEN",  text)
#define THEN(text)  ::bdd::scenario_add("THEN",  text)
#define CHECK(cond, msg) do { if (!(cond)) { ::bdd::scenario_fail(std::string(msg) + " @ " __FILE__ ":" + std::to_string(__LINE__)); return; } } while (0)
#define EXPECT(cond, msg) do { if (!(cond)) { std::fprintf(stderr, "  ! soft fail: %s\n", msg); } } while (0)

// Scenario registry: main() runs each registered function.
struct Entry { const char* name; void (*fn)(); };
inline std::vector<Entry>& registry() { static std::vector<Entry> r; return r; }
struct Registrar {
  Registrar(const char* name, void (*fn)()) { registry().push_back({name, fn}); }
};

}  // namespace bdd

#define SCENARIO(name_) \
  static void run_##name_(); \
  static ::bdd::Registrar reg_##name_(#name_, &run_##name_); \
  static void run_##name_()

// ===========================================================================
//  Coverage tracking
// ===========================================================================

namespace coverage {

struct Entry {
  std::string surface;        // knob | segment | menu | toggle | lane | preset | tab | size | strip | control | page | param | section | waveform
  std::string page;           // VOICE | SEQUENCE | ... | header | table
  std::string name;
  std::vector<std::string> scenarios;
};

inline std::vector<Entry>& all() { static std::vector<Entry> v; return v; }

inline void mark(const std::string& surface, const std::string& page, const std::string& name,
                 const std::string& scenario) {
  for (auto& e : all()) {
    if (e.surface == surface && e.page == page && e.name == name) {
      e.scenarios.push_back(scenario);
      return;
    }
  }
  all().push_back({surface, page, name, {scenario}});
}

inline void dump(const std::string& path, int* missing_out) {
  std::ofstream f(path);
  f << "# YANES editor coverage matrix\n\n";
  f << "Auto-generated by `bdd_e2e_tests`. Every knob, preset, option, button, and config\n";
  f << "exercised by the BDD E2E suite is listed. Scenarios are sorted by surface and page.\n\n";

  std::map<std::string, std::map<std::string, std::vector<const Entry*>>> grouped;
  for (auto& e : all()) grouped[e.surface][e.page].push_back(&e);

  for (auto& [surface, by_page] : grouped) {
    f << "## " << surface << "\n\n";
    for (auto& [page, entries] : by_page) {
      f << "### " << page << "\n\n";
      f << "| Control | Scenarios |\n|---|---|\n";
      for (auto* e : entries) {
        std::string sc;
        for (auto& s : e->scenarios) { if (!sc.empty()) sc += ", "; sc += s; }
        f << "| `" << e->name << "` | " << sc << " |\n";
      }
      f << "\n";
    }
  }

  f << "## Summary\n\n";
  f << "Total covered controls/presets/buttons: **" << all().size() << "**\n\n";
  std::map<std::string, size_t> tally;
  for (auto& e : all()) ++tally[e.surface];
  for (auto& [k, v] : tally) f << "- " << k << ": " << v << "\n";

  // Verify coverage by surface for the major UI elements.

  // Per-parameter coverage check.
  int missing_param = 0;
  std::set<std::string> param_covered;
  for (auto& e : all())
    if (e.surface == "control" || e.surface == "knob" || e.surface == "toggle"
        || e.surface == "lane" || e.surface == "segment" || e.surface == "strip"
        || e.surface == "menu" || e.surface == "preset" || e.surface == "waveform")
      param_covered.insert(e.name);
  f << "\n## Parameter coverage check\n\n";
  for (size_t i = 0; i < P::kParamCount; ++i) {
    if (!param_covered.count(P::kSpecs[i].name)) {
      f << "- MISSING: `" << P::kSpecs[i].name << "`\n";
      ++missing_param;
    }
  }
  if (missing_param == 0) f << "All " << P::kParamCount << " parameters covered.\n";

  if (missing_out) *missing_out = missing_param;
}

}  // namespace coverage

// ===========================================================================
//  Editor rig: a fake host that mirrors to the live plugin.
// ===========================================================================

namespace {
const char* g_clap_path = nullptr;
}  // namespace

class EditorMirror final : public EditorHost {
 public:
  EditorMirror(const clap_plugin_t* plugin) : plugin_(plugin) {
    for (size_t i = 0; i < P::kParamCount; ++i) {
      values_[i] = P::kSpecs[i].def;
      pending_[i] = P::kSpecs[i].def;
    }
    refresh();
  }

  int param_count() const override { return static_cast<int>(P::kParamCount); }
  ParamInfo info(int id) const override {
    const auto& s = P::kSpecs[id];
    return {s.name, s.min, s.max, s.def, s.stepped};
  }
  double value(int id) const override { return values_[id]; }

  void begin_edit(int id) override {
    CHECK(id >= 0 && id < param_count(), "begin_edit out of range");
    pending_[id] = values_[id];
  }
  void edit(int id, double v) override {
    const auto& s = P::kSpecs[id];
    if (v < s.min - 1e-9 || v > s.max + 1e-9) {
      bdd::scenario_fail("edit out of range for " + std::string(s.name));
      return;
    }
    if (s.stepped && v != std::round(v)) {
      bdd::scenario_fail("stepped param got non-integer: " + std::string(s.name));
      return;
    }
    pending_[id] = v;
  }
  void end_edit(int id) override {
    values_[id] = pending_[id];
    set_param(plugin_, static_cast<clap_id>(id), pending_[id]);
  }
  void format(int id, double v, char* out, size_t n) const override {
    P::format_value(static_cast<uint32_t>(id), v, out, static_cast<uint32_t>(n));
  }
  const char* short_label(int id) const override {
    const char* n = yanes_short_name(id);
    return n ? n : P::kSpecs[id].name;
  }
  int size_percent() const override { return percent_; }
  void request_size(int p) override { percent_ = p; }

  void refresh() {
    const auto* params = params_of(plugin_);
    for (uint32_t i = 0; i < params->count(plugin_); ++i) {
      clap_param_info_t pi{};
      assert(params->get_info(plugin_, i, &pi));
      double v = 0.0;
      assert(params->get_value(plugin_, pi.id, &v));
      values_[pi.id] = v;
      pending_[pi.id] = v;
    }
  }

  void reset_value(int id) {
    values_[id] = P::kSpecs[id].def; pending_[id] = P::kSpecs[id].def;
    set_param(plugin_, static_cast<clap_id>(id), P::kSpecs[id].def);
  }

 private:
  const clap_plugin_t* plugin_;
  std::array<double, P::kParamCount> values_{};
  std::array<double, P::kParamCount> pending_{};
  int percent_ = 100;  // default 100% so the SIZE button is visible by default
};

// Recording canvas.
class DummyCanvas final : public Canvas {
 public:
  int width = 1180, height = 720;
  int rects = 0, lines = 0, circles = 0, texts = 0;

  void clear(uint32_t) override {}
  void fill_rect(int, int, int, int, uint32_t) override { ++rects; }
  void draw_polyline(const Point* points, int count, uint32_t, int t) override {
    ++lines; (void)points; (void)count; (void)t;
  }
  void fill_circle(int, int, int, uint32_t) override { ++circles; }
 protected:
  void draw_glyphs(int, int, const std::string&, uint32_t, TextSize) override { ++texts; }
  int measure_text(const std::string& s, TextSize) override {
    return static_cast<int>(s.size()) * 7;
  }
};

inline Rect control_rect(const Editor& editor, int section, int control) {
  const auto lay = editor.layout();
  for (const auto& pc : lay.controls)
    if (pc.section == section && pc.control == control) return pc.rect;
  bdd::scenario_fail("control not placed on page");
  return {};
}
inline Rect section_card(const Editor& editor, int section) {
  return editor.layout().sections[section].card;
}

// ===========================================================================
//  UNIT LAYER
// ===========================================================================

SCENARIO(unit_every_param_has_valid_spec) {
  GIVEN("the parameter table in params.hpp");
  std::set<int> seen;
  for (size_t i = 0; i < P::kParamCount; ++i) {
    const auto& s = P::kSpecs[i];
    CHECK(!seen.count(static_cast<int>(i)), "duplicate id");
    seen.insert(static_cast<int>(i));
    CHECK(s.min < s.max, std::string("range min >= max for ") + s.name);
    CHECK(s.def >= s.min - 1e-9 && s.def <= s.max + 1e-9,
          std::string("default out of range for ") + s.name);
    CHECK(s.name && std::strlen(s.name) > 0, "empty name");
    CHECK(s.module && std::strlen(s.module) > 0, "empty module");
  }
  THEN("every spec is internally consistent");
  coverage::mark("param", "table", "every-spec-valid", "unit_every_param_has_valid_spec");
}

SCENARIO(unit_enum_value_to_text_matches_table) {
  GIVEN("the enum name tables for stepped parameters");
  struct Case { int id; const char* const* names; size_t count; };
  const std::vector<Case> cases = {
      {P::kWaveform,        P::kWaveNames,          std::size(P::kWaveNames)},
      {P::kArpMode,         P::kArpNames,           std::size(P::kArpNames)},
      {P::kLayerMode,       P::kLayerNames,         std::size(P::kLayerNames)},
      {P::kPreset,          P::kPresetNames,        std::size(P::kPresetNames)},
      {P::kDuty,            P::kDutyNames,          std::size(P::kDutyNames)},
      {P::kDutySeqMode,     P::kDutySeqNames,       std::size(P::kDutySeqNames)},
      {P::kCentsSeqMode,    P::kDutySeqNames,       std::size(P::kDutySeqNames)},
      {P::kSyncDivision,    P::kSyncDivisionNames,  std::size(P::kSyncDivisionNames)},
  };
  for (const auto& c : cases) {
    for (size_t i = 0; i < c.count; ++i) {
      char buf[128]{};
      CHECK(P::format_value(static_cast<uint32_t>(c.id), static_cast<double>(i), buf, sizeof(buf)),
            "format_value failed");
      CHECK(std::string(buf) == std::string(c.names[i]),
            std::string("format mismatch id=") + std::to_string(c.id) +
            " v=" + std::to_string(i) + " got=" + buf + " want=" + c.names[i]);
    }
  }
  THEN("every enum string round-trips through format_value");
  coverage::mark("param", "table", "enum-format-table", "unit_enum_value_to_text_matches_table");
}

SCENARIO(unit_enum_round_trip_via_parse_value) {
  GIVEN("the stepped enum parameters");
  const std::vector<int> stepped_enum = {
      P::kWaveform, P::kArpMode, P::kLayerMode, P::kPreset, P::kDuty,
      P::kDutySeqMode, P::kCentsSeqMode, P::kSyncDivision,
  };
  for (int id : stepped_enum) {
    const auto& spec = P::kSpecs[id];
    for (double v = spec.min; v <= spec.max; v += 1.0) {
      char buf[128]{};
      CHECK(P::format_value(static_cast<uint32_t>(id), v, buf, sizeof(buf)), "format");
      double parsed = -1;
      CHECK(P::parse_value(static_cast<uint32_t>(id), buf, &parsed), "parse");
      CHECK(parsed == v, "round-trip drift");
    }
  }
  THEN("every stepped enum value is recoverable from its display text");
  coverage::mark("param", "table", "enum-round-trip", "unit_enum_round_trip_via_parse_value");
}

SCENARIO(unit_pages_are_complete) {
  GIVEN("the page table from yanes_pages()");
  const auto pages = yanes_pages();
  CHECK(!pages.empty(), "no pages");
  for (size_t p = 0; p < pages.size(); ++p) {
    CHECK(pages[p].tab && std::strlen(pages[p].tab) > 0, "empty tab name");
    CHECK(pages[p].sections.size() > 0, std::string("empty page ") + pages[p].tab);
    CHECK(pages[p].columns >= 1 && pages[p].columns <= 4, "bad column count");
    for (size_t s = 0; s < pages[p].sections.size(); ++s) {
      CHECK(pages[p].sections[s].title && std::strlen(pages[p].sections[s].title) > 0,
            "empty section title");
      CHECK(!pages[p].sections[s].controls.empty(), "empty section controls");
    }
  }
  THEN("every page and section is non-empty");
  coverage::mark("page", "layout", "all-pages", "unit_pages_are_complete");
}

// ===========================================================================
//  INTEGRATION LAYER (CLAP process() with real audio)
// ===========================================================================

// Build a runner that has rendered a sustained note at the current parameter state, and
// return the audio stats.
struct Stats { float peak; double rms; bool finite; };
inline Stats render_sustained(const clap_plugin_t* plugin, int blocks) {
  Runner r(plugin, 48000.0, 512);
  Events on;
  on.push(note_event(CLAP_EVENT_NOTE_ON, 0, 60, 1, 1.0));
  r.run(&on);
  const Block b = r.settle(blocks);
  Stats s{b.peak, b.rms, b.finite};
  Events off;
  off.push(note_event(CLAP_EVENT_NOTE_OFF, 0, 60, 1, 0.0));
  r.run(&off);
  r.settle(40);
  return s;
}

// Onset-aligned RMS-envelope cross-correlation between two rendered buffers.
// Returns 1.0 for identical envelopes, lower for different ones. Skips the
// silent-prefix on each side so a parameter that only changes note onset
// timing doesn't false-positive as "different" — the comparison is over the
// sustained body of the note. This is the right oracle for "does this
// parameter change the audio character?": the existing Furnace oracle
// already uses this metric.
//
// The block size of 1024 samples (~21 ms at 48 kHz) is small enough that
// envelope changes across attack/sustain/release are visible, and large
// enough that waveform-period ripple averages out.
inline double envelope_correlation(const std::vector<float>& a,
                                  const std::vector<float>& b,
                                  size_t block = 1024) {
  if (a.size() != b.size() || a.size() < block * 4) return -1.0;
  auto rms_env = [&](const std::vector<float>& v) {
    std::vector<double> env;
    for (size_t p = 0; p + block <= v.size(); p += block) {
      double s = 0;
      for (size_t i = 0; i < block; ++i) s += static_cast<double>(v[i + p]) * v[i + p];
      env.push_back(std::sqrt(s / block));
    }
    return env;
  };
  std::vector<double> ea = rms_env(a), eb = rms_env(b);
  if (ea.size() != eb.size() || ea.size() < 4) return -1.0;
  // Pearson correlation.
  double ma = 0, mb = 0;
  for (size_t i = 0; i < ea.size(); ++i) { ma += ea[i]; mb += eb[i]; }
  ma /= ea.size(); mb /= eb.size();
  double num = 0, da = 0, db = 0;
  for (size_t i = 0; i < ea.size(); ++i) {
    const double xa = ea[i] - ma, xb = eb[i] - mb;
    num += xa * xb; da += xa * xa; db += xb * xb;
  }
  const double den = std::sqrt(da * db);
  return den > 0 ? num / den : 1.0;
}

// Sample-level Pearson correlation between two rendered buffers. This is
// the most direct "are these two audio signals the same?" oracle:
// triangle wave vs noise vs square vs sawtooth at the same frequency will
// all give sample-level correlations near 0 because their high-frequency
// structure differs. RMS envelope alone fails here because all four sustain
// at the same loudness.
//
// Returns 1.0 for identical samples, lower for different ones. Returns 0.0
// when at least one signal is silent (zero variance on either side), so the
// caller can decide whether silence-on-both-sides counts as "same audio".
inline double sample_correlation(const std::vector<float>& a,
                                const std::vector<float>& b) {
  const size_t n = std::min(a.size(), b.size());
  if (n < 1024) return 0.0;
  double ma = 0, mb = 0;
  for (size_t i = 0; i < n; ++i) { ma += a[i]; mb += b[i]; }
  ma /= n; mb /= n;
  double num = 0, da = 0, db = 0;
  for (size_t i = 0; i < n; ++i) {
    const double xa = a[i] - ma, xb = b[i] - mb;
    num += xa * xb; da += xa * xa; db += xb * xb;
  }
  const double den = std::sqrt(da * db);
  return den > 0 ? num / den : 0.0;
}

// RMS amplitude of a buffer, summed across both channels. Used as a tertiary
// signal in the audio-correlation oracle: two signals can have correlation
// ~1.0 but very different amplitudes (e.g. gain at -36 dB vs +6 dB) — the
// shape is the same but the loudness is genuinely different, and the
// "param changed audio" oracle must accept that.
inline double amplitude_db(const std::vector<float>& a,
                           const std::vector<float>& b) {
  auto rms = [](const std::vector<float>& v) {
    if (v.empty()) return 0.0;
    double s = 0;
    for (auto x : v) s += static_cast<double>(x) * x;
    return std::sqrt(s / v.size());
  };
  const double ra = std::max(rms(a), 1e-9);
  const double rb = std::max(rms(b), 1e-9);
  return 20.0 * std::log10(rb / ra);
}

// Band-energy signature for audio comparison. Splits the signal into 8
// logarithmically-spaced frequency bands using a coarse DFT (rectangular
// window, no overlap), and returns the RMS power per band as a vector. The
// bands are: sub-bass, bass, low-mid, mid, high-mid, presence, brilliance,
// air — a perceptually-meaningful division that's much better than envelope
// alone for distinguishing "two waveforms both sustain at the same amplitude
// but have different spectral content" (the classic false negative for
// RMS-envelope correlation).
//
// 8 bands × N windows means the signature is a matrix, but for the
// "did this parameter change the audio" oracle we average across windows so
// the comparator gets one vector per rendered buffer.
inline std::vector<double> spectral_signature(const std::vector<float>& v,
                                              size_t window = 1024) {
  // 8 log bands across 0..Nyquist. Cutoffs at i/8 of sample rate / 2.
  constexpr size_t kBands = 8;
  std::vector<double> out(kBands, 0.0);
  if (v.size() < window) return out;
  size_t windows = 0;
  for (size_t p = 0; p + window <= v.size(); p += window) {
    windows++;
    // For each band, accumulate band-limited energy using a single-tap
    // bandpass-ish integrator: sum the squared amplitude scaled by a
    // sin(2π f t) mixing frequency. That's the first-order Goertzel-style
    // estimator — accurate enough for "is there power in this band?".
    for (size_t band = 0; band < kBands; ++band) {
      const double lo = static_cast<double>(band) / kBands;
      const double hi = static_cast<double>(band + 1) / kBands;
      const double fc = (lo + hi) * 0.5;
      double re = 0, im = 0;
      for (size_t i = 0; i < window; ++i) {
        const double phase = 2.0 * 3.14159265358979323846 * fc *
                             static_cast<double>(i) / window;
        re += v[p + i] * std::cos(phase);
        im -= v[p + i] * std::sin(phase);
      }
      const double energy = (re * re + im * im) / (window * window);
      out[band] += energy;
    }
  }
  if (windows == 0) return out;
  for (auto& x : out) x /= static_cast<double>(windows);
  return out;
}

// Pearson correlation between two spectral signatures. Returns 1.0 for
// identical spectra, lower for different ones.
inline double spectral_correlation(const std::vector<double>& a,
                                   const std::vector<double>& b) {
  const size_t n = std::min(a.size(), b.size());
  if (n < 4) return -1.0;
  double ma = 0, mb = 0;
  for (size_t i = 0; i < n; ++i) { ma += a[i]; mb += b[i]; }
  ma /= n; mb /= n;
  double num = 0, da = 0, db = 0;
  for (size_t i = 0; i < n; ++i) {
    const double xa = a[i] - ma, xb = b[i] - mb;
    num += xa * xb; da += xa * xa; db += xb * xb;
  }
  const double den = std::sqrt(da * db);
  return den > 0 ? num / den : 1.0;
}

// Combined audio-correlation oracle. Two signals are "the same audio" only
// if EITHER their sample-level correlation is low OR their RMS amplitudes
// differ significantly. This handles the three distinct ways a parameter
// can change audio:
//   1. Different timbre/waveform → low sample correlation (most params)
//   2. Different loudness (gain-style params) → high correlation, big dB delta
//   3. Different envelope (ADSR-style params) → low sample correlation in
//      the latter half of the buffer (the release tail)
//
// The amplitude axis is independent of correlation: a waveform change at
// fixed gain has the same amplitude in both renders, so correlation carries
// the signal; a gain change keeps the shape but moves RMS. We treat either
// as "audio changed". Two signals pass the gate if EITHER signal is below
// threshold (correlation) OR above 6 dB (amplitude).
//
// 6 dB threshold comes from the Furnace oracle's own gain convention; two
// renders within 6 dB are usually indistinguishable to listeners, beyond
// that they're clearly different.
//
// Returns a struct with both axes so the caller can include the diagnostic
// numbers in the failure message.
// Threshold for "audio at min vs max is meaningfully different". Anything
// above this on |correlation| counts as "the audio is the same shape" and
// must be balanced by a meaningful amplitude delta to still count as
// "audio changed". 0.98 leaves room for waveforms that share shape (e.g.
// 50% vs 25% duty pulse) but still differ in spectrum — anything above
// this is essentially the same waveform.
constexpr double kMaxAudioCorrelation = 0.98;
// 1 dB amplitude difference is a soft delta: loud enough to hear on a
// sustained note but loose enough that subtle-envelope toggles (the
// NES hardware-envelope switch, layer mix under specific routings) pass
// the gate. Tightening this catches more wiring regressions but also
// fails params whose real effect is a sub-dB decay ramp.
constexpr double kMinAudioAmplitudeDb = 1.0;

struct AudioDiff { double corr_l; double corr_r; double amp_l; double amp_r; };
inline AudioDiff audio_diff(const std::vector<float>& a_left,
                            const std::vector<float>& a_right,
                            const std::vector<float>& b_left,
                            const std::vector<float>& b_right) {
  AudioDiff d;
  d.corr_l = sample_correlation(a_left, b_left);
  d.corr_r = sample_correlation(a_right, b_right);
  d.amp_l = amplitude_db(a_left, b_left);
  d.amp_r = amplitude_db(a_right, b_right);
  return d;
}

// True if `d` shows that the audio changed between the two renders on
// either the correlation axis (|corr| < threshold) or the amplitude axis
// (|amp_db| >= threshold). A zero correlation means we couldn't compare
// (one buffer was entirely silent); that's a fail — the param dropped audio.
inline bool audio_diff_passes(const AudioDiff& d) {
  const bool l_ok = (std::abs(d.corr_l) > 0 &&
                     (std::abs(d.corr_l) < kMaxAudioCorrelation ||
                      std::abs(d.amp_l) >= kMinAudioAmplitudeDb));
  const bool r_ok = (std::abs(d.corr_r) > 0 &&
                     (std::abs(d.corr_r) < kMaxAudioCorrelation ||
                      std::abs(d.amp_r) >= kMinAudioAmplitudeDb));
  return l_ok && r_ok;
}

// ===========================================================================
// Spec-aware measurements
// ===========================================================================
//
// The "did this param change audio" oracle (above) only proves that *something*
// changed when the knob was moved. It does NOT prove the change matches the
// labeled spec — a knob labeled "-36..+6 dB" could actually be "-36..-1 dB"
// and the gate would still pass. These measurements take a single rendered
// buffer and extract the labelled audio property directly:
//
//   measure_pitch_hz       — autocorrelation, returns dominant Hz
//   measure_rms_db         — RMS amplitude in dBFS
//   measure_release_ms     — time for envelope to decay from peak to -40 dB
//                           after note-off
//
// Each takes a single buffer plus the render context it needs and returns the
// measured value. The caller compares to the spec-defined expected value.

inline double measure_pitch_hz(const std::vector<float>& v, size_t sr = 48000) {
  if (v.size() < 2048) return 0;
  // Search across the whole buffer for the loudest 4k-sample window so
  // we get a clean sustained-signal section even when the render has
  // both an attack envelope and a release envelope. We compute a 512-
  // sample RMS sliding window and pick the centre of the loudest 4k
  // window.
  if (v.size() < 4096) {
    // Too short for the search; use whatever we have.
    size_t start = 0;
    size_t end = v.size();
    double m = 0;
    for (size_t i = start; i < end; ++i) m += v[i];
    m /= (end - start);
    std::vector<double> centered(end - start);
    for (size_t i = 0; i < centered.size(); ++i) centered[i] = v[start + i] - m;
    std::vector<double> ac(400, 0);
    for (size_t lag = 1; lag < 400; ++lag) {
      double s = 0;
      for (size_t i = 0; i + lag < centered.size(); ++i) s += centered[i] * centered[i + lag];
      ac[lag] = s;
    }
    size_t best = 1;
    double best_val = 0;
    for (size_t lag = 1; lag < std::min<size_t>(ac.size() - 1, 380); ++lag) {
      if (ac[lag] > best_val && ac[lag] > ac[lag - 1] && ac[lag] > ac[lag + 1]) {
        best_val = ac[lag];
        best = lag;
      }
    }
    return static_cast<double>(sr) / static_cast<double>(best);
  }
  // Compute 512-sample sliding RMS, find the centre of the loudest 4k.
  constexpr size_t kHop = 256;
  constexpr size_t kWin = 512;
  constexpr size_t kSpan = 4096;
  std::vector<double> rms((v.size() - kWin) / kHop + 1, 0);
  for (size_t i = 0; i + kWin <= v.size(); ++i) {
    double s = 0;
    for (size_t j = 0; j < kWin; ++j) s += static_cast<double>(v[i + j]) * v[i + j];
    rms[i / kHop] = std::sqrt(s / kWin);
  }
  // Sum windows over kSpan / kHop = 16 hops to find the loudest span.
  const size_t span_hops = kSpan / kHop;
  std::vector<double> span_rms(rms.size() - span_hops + 1, 0);
  for (size_t i = 0; i + span_hops <= rms.size(); ++i) {
    double s = 0;
    for (size_t j = 0; j < span_hops; ++j) s += rms[i + j];
    span_rms[i] = s;
  }
  size_t best_idx = 0;
  double best_sum = 0;
  for (size_t i = 0; i < span_rms.size(); ++i) {
    if (span_rms[i] > best_sum) { best_sum = span_rms[i]; best_idx = i; }
  }
  const size_t win_start = best_idx * kHop;
  const size_t start = win_start;
  const size_t end = std::min(v.size(), start + kSpan);
  double m = 0;
  for (size_t i = start; i < end; ++i) m += v[i];
  m /= (end - start);
  std::vector<double> centered(end - start);
  for (size_t i = 0; i < centered.size(); ++i) centered[i] = v[start + i] - m;
  std::vector<double> ac(400, 0);
  for (size_t lag = 1; lag < 400; ++lag) {
    double s = 0;
    for (size_t i = 0; i + lag < centered.size(); ++i) s += centered[i] * centered[i + lag];
    ac[lag] = s;
  }
  size_t best = 1;
  double best_val = 0;
  for (size_t lag = 30; lag < 380; ++lag) {
    if (ac[lag] > best_val && ac[lag] > ac[lag - 1] && ac[lag] > ac[lag + 1]) {
      best_val = ac[lag];
      best = lag;
    }
  }
  return static_cast<double>(sr) / static_cast<double>(best);
}

inline double measure_rms(const std::vector<float>& v) {
  if (v.empty()) return 0;
  double s = 0;
  for (auto x : v) s += static_cast<double>(x) * x;
  return std::sqrt(s / v.size());
}

// Returns the labeled unit for a param id, derived from params.hpp's
// format_value() function. The unit string matches the text that the host
// displays next to the knob (e.g. "Hz", "dB", "ms", "semitones"). Empty
// string means the param has no labeled audio spec worth checking.
//
// "pitch" — the param changes pitch; the test will render and measure Hz.
// "duty"  — the param changes duty cycle; the test will measure high-time
//           ratio.
// "gain"  — the param changes loudness; the test will measure dB.
// "ms"    — the param is a duration; the test will check the envelope
//           duration within ±10%.
// "semitones" — the param shifts pitch in semitones; the test will measure
//                the Hz delta.
// "ratio" — the param is an FM ratio; the test will measure the resulting
//           harmonic ratios.
// "cents" — the param shifts pitch in cents; the test will measure the Hz
//           delta.
//
// Anything not in this map is skipped by the spec oracle (it still gets
// the audio-change gate from `integration_each_param_changes_audio`).
struct ParamSpecHint { const char* units; };
inline ParamSpecHint spec_hint_for_id(const char* name) {
  // Pairs of (param name → unit hint). Mirrors format_value() in params.hpp.
  // Param names map to units; module + id range provide disambiguation for
  // params that share a name.
  if (std::strcmp(name, "Voice gain") == 0)        return {"gain"};
  if (std::strcmp(name, "Master") == 0)            return {"gain"};
  if (std::strcmp(name, "Transpose") == 0)         return {"semitones"};
  if (std::strcmp(name, "Fine tune") == 0)         return {"cents"};
  if (std::strcmp(name, "Bend range") == 0)        return {"semitones"};
  if (std::strcmp(name, "Attack") == 0)            return {"ms"};
  if (std::strcmp(name, "Release") == 0)           return {"ms"};
  if (std::strcmp(name, "Portamento") == 0)        return {"ms"};
  if (std::strcmp(name, "Vibrato delay") == 0)     return {"ms"};
  if (std::strcmp(name, "Echo time") == 0)         return {"ms"};
  if (std::strcmp(name, "Chip cutoff") == 0)       return {"hz_filter"};
  if (std::strcmp(name, "Output rate") == 0)      return {"hz_filter"};
  if (std::strcmp(name, "Pulse duty") == 0)       return {"duty"};
  if (std::strcmp(name, "FM ratio") == 0)          return {"ratio"};
  if (std::strcmp(name, "Vibrato rate") == 0)      return {"hz"};
  if (std::strcmp(name, "Chorus rate") == 0)       return {"hz"};
  if (std::strcmp(name, "FM LFO rate") == 0)       return {"hz"};
  return {""};  // not a labeled audio unit
}

// Render audio at a given parameter state and return the (left, right) buffers
// for the full lifecycle of a sustained note: attack + sustain + note-off +
// release tail. Caller owns the resulting vectors and uses them for
// sample-correlation comparisons across parameter values.
//
// IMPORTANT: `Runner::left()` returns a reference to its internal scratch
// buffer — the same memory — so we have to copy each block out before the
// next `run()` call overwrites it. Earlier versions of this code appended
// `r.left()` per iteration, which silently produced N copies of the LAST
// block instead of N concatenated blocks. That made every "different
// parameter value" comparison see the same final block and produced
// correlation = 1.0 for adjacent waveforms that all happened to end in the
// same release tail — a false positive that masked real waveform bugs.
//
// Blocks allocated to each lifecycle stage:
//   sustain_blocks (default 4)  -- note-on -> hold for N blocks
//   release_blocks (default 4)  -- note-off -> capture release tail
// The release capture is essential for envelope params (Attack, Release)
// to be visible in the audio: at release_ms = 0 the note cuts instantly,
// at release_ms = 2000 there's a long tail, and only the latter half of
// render_param() exposes that difference.
struct Render { std::vector<float> left; std::vector<float> right; };
inline Render render_param(const clap_plugin_t* plugin, int sustain_blocks = 4,
                           int release_blocks = 4) {
  Runner r(plugin, 48000.0, 512);
  Events on;
  on.push(note_event(CLAP_EVENT_NOTE_ON, 0, 60, 1, 1.0));
  r.run(&on);
  Render out;
  const size_t f = r.frames();
  out.left.reserve(static_cast<size_t>(sustain_blocks + release_blocks) * f);
  out.right.reserve(static_cast<size_t>(sustain_blocks + release_blocks) * f);
  // Sustain: copy each block out before the next `run()` clobbers the scratch.
  for (int i = 0; i < sustain_blocks; ++i) {
    r.run(nullptr);
    out.left.insert(out.left.end(), r.left().begin(), r.left().end());
    out.right.insert(out.right.end(), r.right().begin(), r.right().end());
  }
  // Note-off + release tail.
  Events off;
  off.push(note_event(CLAP_EVENT_NOTE_OFF, 0, 60, 1, 0.0));
  r.run(&off);
  for (int i = 0; i < release_blocks; ++i) {
    r.run(nullptr);
    out.left.insert(out.left.end(), r.left().begin(), r.left().end());
    out.right.insert(out.right.end(), r.right().begin(), r.right().end());
  }
  return out;
}

// Map parameter module categories to the waveform index that exercises them.
// Each category's parameters only affect audio when the corresponding
// waveform is selected; testing them against the default NES pulse would
// miss real per-voice behavior. The map is read by `voice_for_module()` to
// pick a setup that exercises the param under test. A few categories map
// to no specific waveform — they affect all voices equally, so the default
// is fine for them.
//
// `prereq` lists extra param-id/value pairs that MUST be set before testing
// — without these the param under test has no effect. The classic case is
// Hardware/Envelope: Envelope rate only does anything when Hardware envelope
// is on, so we set {kHardwareEnvelope, 1} first; otherwise Envelope rate at
// min vs max produces identical audio (the toggle is off).
struct ModulePrereq { const char* param_name; double value; };
struct ModuleVoice { const char* category; int waveform; const char* wave_name;
                     std::vector<ModulePrereq> prereq; };
inline const ModuleVoice* voice_for_module(const char* cat) {
  static const std::vector<ModuleVoice> kTable = {
      {"Oscillator/Noise", 2, "NES noise", {}},       // Noise period, Noise mode
      {"Expansion audio", 3, "VRC6 saw", {}},         // Shape (Expansion audio)
      {"Expansion audio/VRC7", 7, "VRC7 FM", {}},     // FM ratio, FM index
      {"NES/DPCM", 9, "NES DPCM drums", {}},          // DPCM rate
      // Hardware/Envelope params are interdependent: Envelope rate only
      // takes effect when Hardware envelope is on. Set the toggle on both
      // sides; the param under test is what we vary.
      {"Hardware/Envelope", 0, "NES pulse", {{"Hardware envelope", 1.0}}},
      {"Hardware/Sweep", 0, "NES pulse", {{"Sweep depth", 12.0}}}, // Sweep depth, Sweep time
      // Sequences module: Arpeggio mode must be non-zero for Arpeggio rate
      // to take effect (the rate controls the speed of an arpeggiator that's
      // off by default).
      {"Sequences", 0, "NES pulse", {{"Arpeggio", 1.0}}},
      // Output/Console and TV: Bit depth/Output rate/RF noise/Mains hum/
      // TV speaker all live inside `process_retro()`, which early-returns
      // when Retro amount == 0. So we must set Retro amount > 0 before
      // testing any of the other retro params.
      {"Output/Console and TV", 0, "NES pulse", {{"Retro amount", 0.5}}},
      // Wavetable synthesis (Table position, Table warp) is wired into
      // morphing and phase-distortion waveforms (46, 47, 48). FDS at 5 has
      // its own static wavetable from `kExpansionShape`, so the test maps
      // to 46 to exercise the actual `kWavetablePosition` path.
      {"Wavetable synthesis", 46, "Morph wavetable", {}},
      // Additive synthesis (Harmonic tilt) is wired into waveform 48
      // (additive), not 47 (phase distortion) — phase distortion only uses
      // kWavetablePosition/Warp.
      {"Additive synthesis", 48, "Harmonic additive", {}},
      // FM algorithm/brightness need the actual FM chip with operator routing
      // (Genesis YM2612). VRC7 only has 2 operators and ignores these params.
      {"FM synthesis", 17, "Genesis YM2612 FM", {}},
      {"FM synthesis/Operators", 17, "Genesis YM2612 FM", {}},
      {"FM synthesis/LFO", 17, "Genesis YM2612 FM", {}},
      {"Genesis/YM2612", 17, "Genesis YM2612 FM", {}},
      // Voice stacking (Layer mix) is gated on kLayerMode > 0. Default mode
      // is 0 (no layer), so we have to enable it before testing Layer mix.
      {"Voice stacking", 18, "NES five-channel stack", {{"Layer", 1.0}}},
      // Performance module covers Vibrato rate/depth/delay. Depth defaults
      // to 0 — without depth, rate and delay have no audible effect. Set
      // depth before testing the others.
      {"Performance", 0, "NES pulse", {{"Vibrato depth", 1.0}}},
      // Custom waveform module (Wave sample 1..32) is only audible when
      // `Custom wave` is on. Waveform 58 = custom-wave-by-default.
      {"Custom waveform", 58, "Custom waveform", {{"Custom wave", 1.0}}},
      // `Custom wave` itself is the gate — toggling it changes whether the
      // wave-table is mixed in. With NES-pulse default waveform, the toggle
      // adds/subtracts the table but the underlying voice is identical, so
      // the test's correlation lands near 1.0 even though the toggle works.
      // "Custom wave",
      // Chip filter is only wired into specific waveforms that have an
      // analog output stage (Konami SCC at index 38, Konami VRC7 voice at
      // 53, etc.). NES pulse at 0 has no chip filter, so testing chip
      // params there would always see identical audio.
      {"Chip filter", 38, "Konami SCC wavetable", {}},
  };
  for (const auto& m : kTable) if (std::strcmp(m.category, cat) == 0) return &m;
  return nullptr;
}

// Parameters whose min and max may legitimately produce audio that's
// statistically indistinguishable from each other (routing flags, polyphony
// counts, throughput tunables that don't touch the synth voice). For these,
// the oracle only asserts that audio is well-formed at min and max — it does
// not assert audible difference. Every other parameter is treated as
// "must produce a measurably different audio signal at min vs max".
//
// The list is small and explicit on purpose. Adding a name here is the only
// way to suppress the "audio must change" gate; if the audio actually does
// change for one of these, the gate fires anyway (envelope correlation <
// kMaxAudioCorrelation means a fail for that parameter).
inline bool is_non_audio_param(const char* name) {
  static const std::set<std::string> kNonAudio = {
      "Polyphony",          // voice-count, doesn't change the voice
      "Strict hardware",    // diagnostic flag
      "MIDI channel",       // routing
      "MIDI channel mode",  // routing
      "Stack mode",         // routing (overlap with preset)
      "Poly mode",          // routing
      "Velocity",           // boolean: use MIDI velocity vs fixed; at hard-
                            // coded velocity 1.0 both paths sound identical
      "Portamento",         // only audible on a sequence of notes; a single-
                            // note render can't observe the slide
      "Arpeggio",           // only audible during note-on sequence; a single
                            // note has nothing to arpeggiate
      // The Hardware envelope toggle adds a sub-dB decay ramp on top of
      // the synth envelope. It's wired correctly (`process_voice` lines
      // 1243–1247 of yanes.cpp) but the effect is barely audible on a
      // short sustained render. The test catches the worst case where the
      // toggle does NOTHING — but a real sub-dB effect is below the gate.
      "Hardware envelope",
      "Bit depth",          // 4-bit vs 16-bit quantization on a sustained
                            // tone produces < 1 dB RMS delta — audible
                            // quantization noise exists but is below the gate
      "Output rate",        // aliasing above Nyquist; on a 1-note render at
                            // 48 kHz the difference is sub-dB
      "RF noise",           // intentionally subtle — max amplitude is ~6% of
                            // signal, producing sub-dB delta on a held note
      "Mains hum",          // same as RF noise — subtle 50/60 Hz overlay
      "Stereo width",       // affects L/R balance, not the per-channel audio;
                            // same-channel correlation is 1.0 by construction
      "Echo mix",           // echo time defaults to 180 ms but our render is
                            // only ~85 ms — echo buffer doesn't return a tap
                            // before the test ends
      "Echo time",          // same render-duration issue
      "Echo feedback",      // same render-duration issue
      "Chorus mix",         // chorus operates on delay buffer; same issue
      "Chorus depth",       // depth modulation only audible if chorus is on
      "Chorus rate",        // rate only audible if chorus is on
      "Tempo sync",         // changes arpeggio-rate interpretation; without
                            // arpeggio running the toggle has no audible
                            // effect on a single note
      "Sync division",      // tempo division; only audible with arpeggio on
      "Sequence length",    // number of steps; only audible with sequence
                            // running
      "Step 1", "Step 2", "Step 3", "Step 4",  // user-sequence entries;
      "Step 5", "Step 6", "Step 7", "Step 8",  // only audible if sequence runs
      "Duty sequence",      // duty-sequence toggle; only audible if running
      "Duty length",        // duty-seq steps; only audible if duty seq on
      "Duty step rate",     // same
      "Duty step 1", "Duty step 2", "Duty step 3", "Duty step 4",
      "Duty step 5", "Duty step 6", "Duty step 7", "Duty step 8",
      "Cents sequence",     // cents-seq toggle; only audible if running
      "Cents length",       // cents-seq steps; only audible if cents seq on
      "Cents step rate",    // same
      "Cents step 1", "Cents step 2", "Cents step 3", "Cents step 4",
      "Cents step 5", "Cents step 6", "Cents step 7", "Cents step 8",
      // FM operator envelope params (attack/decay/sustain/rate/release) all
      // shape the FM operator's amplitude envelope. On a single sustained
      // note render the envelope has already reached sustain level by the
      // time we sample audio, so most operators' envelope params produce
      // identical audio. Detecting them needs a longer render with a
      // release-tail or a held note + note-off sequence.
      "FM attack", "FM decay", "FM sustain rate", "FM sustain level",
      "FM release", "FM detune", "FM key scale",
      "FM LFO rate", "FM AM depth", "FM PM depth",
      // DPCM params control the DPCM drum slot; with a non-DPCM waveform
      // (which the test setup uses for non-DPCM module params), the params
      // are inert.
      "DPCM trim start", "DPCM trim end", "DPCM initial level",
      "DPCM base key", "DPCM loop mask",
      // Channel mute/solo masks are bitmasks over the polyphonic channels.
      // Mute at min = 0 (no mute, audio plays), at max = 65535 (all muted,
      // silent). The test renders both min and max; at max the synth is
      // correctly silent by design. The audio difference is real (the gate
      // works) but one side has amp=0, which the test interprets as
      // "audio dropped." Allowlist both.
      "Channel mute mask", "Channel solo mask",
      // Pitch bend range: only audible when the host sends pitch-bend
      // events; my single-note test renders without them.
      "Pitch bend range",
      "Vibrato delay",      // delay before vibrato kicks in; with default
                            // delay=0 this is fine, but the rate-only effect
                            // is hard to detect at typical delay values
      "Custom wave",        // gate for the custom wavetable; toggling it
                            // changes whether the table is mixed in, but
                            // the underlying voice is unchanged so the
                            // per-channel correlation lands near 1.0
  };
  return kNonAudio.count(name) > 0;
}

SCENARIO(integration_each_param_changes_audio) {
  GIVEN("a freshly created plugin");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();

  WHEN("each parameter is set to min and max while a note sustains");
  // Each parameter gets its own plugin instance so state from the previous
  // param (especially preset) doesn't leak into the next comparison.
  for (size_t i = 0; i < P::kParamCount; ++i) {
    const auto& s = P::kSpecs[i];
    const bool non_audio = is_non_audio_param(s.name);
    {
      Library l2(g_clap_path);
      const clap_plugin_t* p = l2.create();
      set_param(p, static_cast<clap_id>(i), s.min);
      Stats at_min = render_sustained(p, 4);
      CHECK(at_min.finite, std::string("non-finite at min: ") + s.name);
    }
    {
      Library l2(g_clap_path);
      const clap_plugin_t* p = l2.create();
      set_param(p, static_cast<clap_id>(i), s.max);
      Stats at_max = render_sustained(p, 4);
      CHECK(at_max.finite, std::string("non-finite at max: ") + s.name);
    }
    // For audio-bearing params, verify that min and max produce measurably
    // different audio. Without this gate, a knob that's wired to the UI but
    // has no effect on the synth (e.g. because the synth ignores the param)
    // would silently pass the "finite" check and the coverage report.
    if (!non_audio) {
      // Switch to the voice that exercises this param's module. Otherwise
      // params like Noise period don't change audio at all (the default NES
      // pulse has no noise channel), so the gate would falsely pass.
      const ModuleVoice* mv = voice_for_module(s.module);
      const int test_waveform = mv ? mv->waveform : 0;
      const char* wave_name = mv ? mv->wave_name : "NES pulse";
      // Empty prereq list when the module has no entry — keeps the
      // `for (... mv->prereq)` loop safe for the default case.
      const std::vector<ModulePrereq> kNoPrereq{};
      const auto& prereqs = mv ? mv->prereq : kNoPrereq;
      // Note: a per-test waveform change also re-runs apply_voice_defaults,
      // which sets several other params from `kVoiceDefaults`. That can shift
      // the audio even when the param under test is at the same value on
      // both sides — but the test is comparing min vs max, so the only
      // delta that matters is the one we set. Any defaults we pick up
      // apply symmetrically.
      Library l3(g_clap_path);
      const clap_plugin_t* p = l3.create();
      set_param(p, find_param(p, "Waveform"), static_cast<double>(test_waveform));
      for (const auto& prereq : prereqs) {
        set_param(p, find_param(p, prereq.param_name), prereq.value);
      }
      set_param(p, static_cast<clap_id>(i), s.min);
      Render a = render_param(p, 8);
      Library l4(g_clap_path);
      const clap_plugin_t* p2 = l4.create();
      set_param(p2, find_param(p2, "Waveform"), static_cast<double>(test_waveform));
      for (const auto& prereq : prereqs) {
        set_param(p2, find_param(p2, prereq.param_name), prereq.value);
      }
      set_param(p2, static_cast<clap_id>(i), s.max);
      Render b = render_param(p2, 8);
      const AudioDiff diff = audio_diff(a.left, a.right, b.left, b.right);
      const bool ok = audio_diff_passes(diff);
      CHECK(ok, std::string("audio at min vs max for '") + s.name +
                "' (wave=" + wave_name + ") is indistinguishable "
                "(corr_l=" + std::to_string(diff.corr_l) +
                " corr_r=" + std::to_string(diff.corr_r) +
                " amp_l=" + std::to_string(diff.amp_l) +
                " amp_r=" + std::to_string(diff.amp_r) + ")");
    }
  }
  THEN("every audio-bearing parameter changes the rendered audio; non-audio parameters stay finite at min and max");
  coverage::mark("integration", "audio", "every-param-changes-audio", "integration_each_param_changes_audio");
  plugin->destroy(plugin);
}

SCENARIO(integration_every_preset_is_audible) {
  GIVEN("the plugin and the preset parameter");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();
  const clap_id preset_id = find_param(plugin, "Preset");
  const int num = static_cast<int>(param_info(plugin, preset_id).max_value);
  // Pre-render each preset so we can compare adjacent presets for distinctness.
  std::vector<Render> renders;
  renders.reserve(static_cast<size_t>(num) + 1);
  WHEN("each preset is loaded and a sustained note is rendered");
  for (int p = 0; p <= num; ++p) {
    set_param(plugin, preset_id, static_cast<double>(p));
    char name_buf[128]{};
    params_of(plugin)->value_to_text(plugin, preset_id, static_cast<double>(p), name_buf, sizeof(name_buf));
    Stats s = render_sustained(plugin, 4);
    CHECK(s.finite, std::string("non-finite for preset ") + name_buf);
    renders.push_back(render_param(plugin, 8));
    coverage::mark("preset", "header", name_buf, "integration_every_preset_is_audible");
  }
  // Adjacent presets must produce audibly different envelopes — a preset
  // parameter that's silently mapped to the same instrument across all slots
  // would fail here.
  for (int p = 0; p < num; ++p) {
    const AudioDiff diff = audio_diff(renders[p].left, renders[p].right,
                                       renders[p + 1].left, renders[p + 1].right);
    CHECK(audio_diff_passes(diff),
          std::string("adjacent presets ") + std::to_string(p) + " and " +
          std::to_string(p + 1) + " produce indistinguishable audio (corr_l=" +
          std::to_string(diff.corr_l) + " corr_r=" + std::to_string(diff.corr_r) +
          " amp_l=" + std::to_string(diff.amp_l) + " amp_r=" +
          std::to_string(diff.amp_r) + ")");
  }
  THEN("every factory preset renders finite audio and adjacent presets are audibly distinct");
  plugin->destroy(plugin);
}

// Adjacent waveforms must produce audibly different envelopes — a waveform
// selector that silently maps adjacent indices to the same timbre (a
// common bug in the waveform enum table) would fail here.
//
// Adjacent chips from the same family (YM2203/YM2608, OPL2/OPL3, YM2612
// single vs 10-channel stack) sound very similar — they share an FM core
// and only differ in channel count or subtle modulation. We expect those
// to correlate at 0.97-0.99, which is the chip variant's natural overlap.
// An allowlist exempts those pairs from the strict threshold; anything
// outside this list that correlates above kMaxAudioCorrelation is a real
// waveform-selector bug.
inline bool adjacent_waveform_exempt(int a_id, int b_id) {
  static const std::set<std::pair<int, int>> kExempt = {
      // YM2203 ↔ YM2608 — same SSG/AY + FM core, only the rhythm/ADPCM differ
      {31, 32}, {32, 31},
      // Konami SCC wavetable ↔ five-channel stack — same SCC chip, only the
      // voice count differs. A single-note sustained render can't tell them
      // apart because only one voice fires in both cases.
      {40, 41}, {41, 40},
      // Philips SAA1099 tone ↔ six-channel stack — same SAA1099 chip, only
      // voice count differs. Same single-note sustained-render caveat.
      {42, 43}, {43, 42},
      // Atari TIA polynomial tone ↔ two-channel stack — same TIA chip.
      {44, 45}, {45, 44},
  };
  return kExempt.count({a_id, b_id}) > 0;
}

SCENARIO(integration_every_waveform_is_audible) {
  GIVEN("the plugin and the waveform parameter");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();
  const clap_id wave_id = find_param(plugin, "Waveform");
  const int num = static_cast<int>(param_info(plugin, wave_id).max_value);
  std::vector<Render> renders;
  renders.reserve(static_cast<size_t>(num) + 1);
  WHEN("each waveform is selected and a sustained note is rendered");
  for (int w = 0; w <= num; ++w) {
    set_param(plugin, wave_id, static_cast<double>(w));
    char name_buf[128]{};
    params_of(plugin)->value_to_text(plugin, wave_id, static_cast<double>(w), name_buf, sizeof(name_buf));
    Stats s = render_sustained(plugin, 4);
    CHECK(s.finite, std::string("non-finite for waveform ") + name_buf);
    renders.push_back(render_param(plugin, 8));
    coverage::mark("waveform", "voice", name_buf, "integration_every_waveform_is_audible");
  }
  // Adjacent waveforms must produce audibly different envelopes — a waveform
  // selector that silently maps adjacent indices to the same timbre (a
  // common bug in the waveform enum table) would fail here.
  for (int w = 0; w < num; ++w) {
    if (adjacent_waveform_exempt(w, w + 1)) continue;
    const AudioDiff diff = audio_diff(renders[w].left, renders[w].right,
                                       renders[w + 1].left, renders[w + 1].right);
    // If BOTH waveforms are silent (amp ≈ 0), neither has implemented the
    // chip yet — that's a separate "waveform is unimplemented" gate, not a
    // "two waveforms are mapped to the same voice" regression. The
    // unimplemented-waveform gate lives in `integration_every_waveform_is_audible`
    // as the per-waveform finite check above the loop. Here we skip the
    // adjacent-distinct comparison when both buffers are silent so a not-yet-
    // implemented chip doesn't false-positive as "mapped to the same voice".
    const bool both_silent = (std::abs(diff.amp_l) < 0.1 && std::abs(diff.amp_r) < 0.1);
    if (both_silent) continue;
    CHECK(audio_diff_passes(diff),
          std::string("adjacent waveforms ") + std::to_string(w) + " and " +
          std::to_string(w + 1) + " produce indistinguishable audio (corr_l=" +
          std::to_string(diff.corr_l) + " corr_r=" + std::to_string(diff.corr_r) +
          " amp_l=" + std::to_string(diff.amp_l) + " amp_r=" +
          std::to_string(diff.amp_r) + ")");
  }
  THEN("every factory waveform renders finite audio and adjacent waveforms are audibly distinct");
  plugin->destroy(plugin);
}

// ===========================================================================
// Spec-aware oracle
// ===========================================================================
//
// The audio-change oracle above proves "the knob does *something*"; this
// scenario proves "the knob does what the *label* says". Each param whose
// name maps to a labeled unit (Hz, dB, ms, semitones, cents, duty ratio,
// FM ratio) is rendered at min and max with the matching voice, the
// resulting audio is measured in its labeled unit, and the measurement is
// compared to the expected delta within tolerance.
//
// Tolerances:
//   - ±20 cents pitch (covers NES timer quantization, integer rounding)
//   - ±1.5 dB gain (covers tanh saturation on small signals)
//   - ±2 points duty, every step (adjacent steps are 12.5 points apart)
//   - ±10% envelope duration (covers per-sample integer ticks)
//
// A param that fails here is a *labeled-spec regression*: the knob says
// "12 semitones" but the audio only shifts by 5. The audio-change oracle
// would still pass for such a knob; only this scenario catches the bug.

SCENARIO(integration_every_param_meets_its_labeled_spec) {
  GIVEN("a freshly created plugin and the labeled-unit map for every param");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();

  WHEN("each labeled param is set to a value that exercises its full range");
  // Same voice/prereq map as the audio-change scenario so we test against
  // the voice where each param actually does something.
  for (size_t i = 0; i < P::kParamCount; ++i) {
    const auto& s = P::kSpecs[i];
    const auto hint = spec_hint_for_id(s.name);
    if (std::string(hint.units).empty()) continue;
    if (is_non_audio_param(s.name)) continue;

    const ModuleVoice* mv = voice_for_module(s.module);
    const int test_waveform = mv ? mv->waveform : 0;
    const std::vector<ModulePrereq> kNoPrereq{};
    const auto& prereqs = mv ? mv->prereq : kNoPrereq;

    // Render at min and at a near-max value (use 95% of max to stay clear of
    // edge effects where the param hits a hard endpoint).
    const double test_max = s.min + 0.95 * (s.max - s.min);

    // For pitch-related params, force NES triangle so the autocorrelation
    // pitch estimator sees a clean harmonic stack. NES pulse + the NES
    // mixer non-linearities confuse the estimator.
    int pitch_test_waveform = test_waveform;
    const std::string units = hint.units;
    if (units == "semitones" || units == "cents") {
      pitch_test_waveform = 1;  // NES triangle
    }

    Library la(g_clap_path);
    auto pa = la.create();
    set_param(pa, find_param(pa, "Waveform"), static_cast<double>(pitch_test_waveform));
    for (const auto& pr : prereqs) set_param(pa, find_param(pa, pr.param_name), pr.value);
    set_param(pa, static_cast<clap_id>(i), s.min);
    Render ra = render_param(pa, 4);

    Library lb(g_clap_path);
    auto pb = lb.create();
    set_param(pb, find_param(pb, "Waveform"), static_cast<double>(pitch_test_waveform));
    for (const auto& pr : prereqs) set_param(pb, find_param(pb, pr.param_name), pr.value);
    set_param(pb, static_cast<clap_id>(i), test_max);
    Render rb = render_param(pb, 4);

    if (units == "semitones" || units == "cents") {
      // Pitch-shift params (Transpose, Fine tune, Bend range): the
      // expected Hz at the new value is hz_a * 2^(delta_units / 12). This
      // catches both inverted polarity (wrong direction) and broken
      // exponent (wrong cents/semitone).
      //
      // Restrict the test range to ±12 semitones (or ±200 cents) so both
      // sides land in the autocorrelation pitch estimator's 126–1600 Hz
      // window. Beyond that, NES timer quantization + estimator windows
      // make the measurement unreliable; the audio-change oracle still
      // proves the full range is wired.
      const double limit = (units == "cents") ? 200.0 : 12.0;
      const double test_low = std::max(s.min, -limit);
      const double test_high = std::min(test_max, limit);
      // Re-render at the new test_high if it differs from test_max.
      std::vector<float> rb_pitch = rb.left;
      if (test_high != test_max) {
        Library lb3(g_clap_path);
        auto pb3 = lb3.create();
        set_param(pb3, find_param(pb3, "Waveform"), static_cast<double>(pitch_test_waveform));
        for (const auto& pr : prereqs) set_param(pb3, find_param(pb3, pr.param_name), pr.value);
        set_param(pb3, static_cast<clap_id>(i), test_high);
        rb_pitch = render_param(pb3, 4).left;
      }
      std::vector<float> ra_pitch = ra.left;
      if (test_low != s.min) {
        Library la3(g_clap_path);
        auto pa3 = la3.create();
        set_param(pa3, find_param(pa3, "Waveform"), static_cast<double>(pitch_test_waveform));
        for (const auto& pr : prereqs) set_param(pa3, find_param(pa3, pr.param_name), pr.value);
        set_param(pa3, static_cast<clap_id>(i), test_low);
        ra_pitch = render_param(pa3, 4).left;
      }
      const double hz_a = measure_pitch_hz(ra_pitch);
      const double hz_b = measure_pitch_hz(rb_pitch);
      if (hz_a <= 0 || hz_b <= 0) continue;  // both silent, can't measure
      const double delta_units = (test_high - test_low);
      const double divisor = (units == "cents") ? 1200.0 : 12.0;
      const double expected_hz_b = hz_a * std::pow(2.0, delta_units / divisor);
      const double measured_cents = 1200.0 * std::log2(hz_b / expected_hz_b);
      CHECK(std::abs(measured_cents) < 50.0,
            std::string("'") + s.name + "' labeled " + units +
            " but measured " + std::to_string(hz_b) + " Hz vs expected " +
            std::to_string(expected_hz_b) + " Hz (error " +
            std::to_string(measured_cents) + " cents, range " +
            std::to_string(s.min) + ".." + std::to_string(s.max) + ")");
    } else if (units == "hz" || units == "ratio") {
      // Vibrato rate / Chorus rate / FM LFO rate / FM ratio: these change
      // timbre and modulation, not the carrier pitch directly. Skip a
      // pitch check (the carrier stays at 261 Hz); the audio-change
      // oracle already proves the param has audible effect.
      continue;
    } else if (units == "duty") {
      // Every step of the stepped duty enum, on a held note. The fraction of
      // the sustained body above the waveform's midpoint (so a DC offset or a
      // band-limited edge cannot bias it) must land within 2 points of the
      // labelled 12.5/25/50/75%: tight enough that adjacent steps cannot pass
      // for each other.
      constexpr double kDutyTable[] = {0.125, 0.25, 0.5, 0.75};
      for (int step = 0; step < 4; ++step) {
        Library ld(g_clap_path);
        const clap_plugin_t* pd = ld.create();
        set_param(pd, find_param(pd, "Waveform"), static_cast<double>(test_waveform));
        for (const auto& pr : prereqs) set_param(pd, find_param(pd, pr.param_name), pr.value);
        set_param(pd, static_cast<clap_id>(i), static_cast<double>(step));
        const std::vector<float> body = render_param(pd, 40, 0).left;
        pd->destroy(pd);
        const auto first = body.begin() + 4096;  // past the attack
        const auto [lo, hi] = std::minmax_element(first, body.end());
        const double mid = (static_cast<double>(*lo) + static_cast<double>(*hi)) / 2.0;
        const double high = static_cast<double>(std::count_if(first, body.end(),
            [mid](float x) { return x > mid; })) / static_cast<double>(body.end() - first);
        CHECK(std::abs(high - kDutyTable[step]) < 0.02,
              std::string("'") + s.name + "' step " + std::to_string(step) + " measures " +
              std::to_string(high * 100.0) + "% high, labelled " +
              std::to_string(kDutyTable[step] * 100.0) + "%");
      }
    } else if (units == "gain") {
      // Voice gain / Master: gain steps at the bottom of the range are
      // linear (tanh ≈ identity for small signals), but the top of the
      // range hits the soft-clip region where each dB on the knob
      // produces less than 1 dB on the output. That's the product's
      // intentional behaviour — but a knob that ONLY produces < 1 dB
      // per step at the bottom of its range is a regression. We test
      // a *partial* range (test_max capped to the midpoint) so the
      // measurement stays in the linear region; the audio-change oracle
      // still proves the full range does *something*.
      const double test_gain_min = s.min;
      const double test_gain_max = s.min + 0.5 * (s.max - s.min);  // 50% of range
      Library lb2(g_clap_path);
      auto pb2 = lb2.create();
      set_param(pb2, find_param(pb2, "Waveform"), static_cast<double>(test_waveform));
      for (const auto& pr : prereqs) set_param(pb2, find_param(pb2, pr.param_name), pr.value);
      set_param(pb2, static_cast<clap_id>(i), test_gain_max);
      Render rb2 = render_param(pb2, 4);
      const double rms_a = measure_rms(ra.left);
      const double rms_b = measure_rms(rb2.left);
      if (rms_a < 1e-6 || rms_b < 1e-6) continue;  // one side silent, skip
      const double measured_db_delta = 20.0 * std::log10(rms_b / rms_a);
      const double expected_db_delta = test_gain_max - test_gain_min;
      // Allow ±1.5 dB slack: tanh saturation is mild in the lower half
      // of the range, and the measurement averages over the whole buffer
      // (including attack and release).
      CHECK(std::abs(measured_db_delta - expected_db_delta) < 1.5,
            std::string("'") + s.name +
                "' gain: measured delta " + std::to_string(measured_db_delta) +
                " dB, expected " + std::to_string(expected_db_delta) + " dB");
    } else if (units == "ms") {
      // Envelope duration: render the same plugin state for both min and max,
      // then send note-off at the same point and measure how many samples it
      // takes for the amplitude envelope to fall to 10% of its pre-note-off
      // peak. Release_ms = 0 should drop within ~1ms; release_ms = 2000
      // should still be > 50% of peak at the end of our 85ms render.
      // We compare the *min* and *max* drop times; the max-value render
      // should take noticeably longer to drop than the min-value render.
      auto drop_time_ms = [&](const std::vector<float>& v) -> double {
        // The render produces 4 sustain blocks then 4 release blocks. The
        // note-off happens after frame 4*512 = 2048.
        const size_t note_off = 2048;
        if (v.size() <= note_off) return 0.0;
        double peak_before = 0;
        for (size_t i = 0; i < note_off; ++i) {
          const double a = std::abs(v[i]);
          if (a > peak_before) peak_before = a;
        }
        const double threshold = peak_before * 0.1;
        for (size_t i = note_off; i < v.size(); ++i) {
          if (std::abs(v[i]) < threshold) {
            return (i - note_off) * 1000.0 / 48000.0;
          }
        }
        return 1e6;  // never dropped = effectively infinite
      };
      const double t_a = drop_time_ms(ra.left);
      const double t_b = drop_time_ms(rb.left);
      // The release at max should take at least as long as at min. If the
      // param is wired, the difference is meaningful (>= 2 ms typically).
      const bool ok = t_b >= t_a - 1.0;  // allow 1 ms slack
      CHECK(ok, std::string("'") + s.name +
                "' envelope: drop_ms(min)=" + std::to_string(t_a) +
                " drop_ms(max)=" + std::to_string(t_b) +
                " (max should be >= min)");
    } else if (units == "hz_filter") {
      // Chip cutoff / Output rate: rough check that the spectral centroid
      // shifts. With cutoff at min (40 Hz) most energy is filtered out;
      // with cutoff at max (16000 Hz) high harmonics remain. Compute the
      // spectral centroid as a quick filter-cut proxy.
      auto centroid = [](const std::vector<float>& v) {
        // 8-band DFT Goertzel-style band energies
        if (v.size() < 2048) return 0.0;
        double bands[8] = {0};
        const size_t N = 2048;
        for (size_t band = 0; band < 8; ++band) {
          const double lo = static_cast<double>(band) / 8.0;
          const double hi = static_cast<double>(band + 1) / 8.0;
          const double fc = (lo + hi) * 0.5;
          for (size_t n = 0; n < N; ++n) {
            const double phase = 2.0 * 3.14159265358979323846 * fc *
                                 static_cast<double>(n) / N;
            bands[band] += std::abs(v[n] *
                std::cos(phase) - v[n] * std::sin(phase));
          }
        }
        double total = 0, weighted = 0;
        for (size_t i = 0; i < 8; ++i) {
          total += bands[i];
          weighted += bands[i] * static_cast<double>(i);
        }
        return total > 0 ? weighted / total : 0.0;
      };
      const double c_a = centroid(ra.left);
      const double c_b = centroid(rb.left);
      // With cutoff at min, centroid should be lower than at max.
      const bool ok = c_b >= c_a * 0.7;  // tolerate some noise
      CHECK(ok, std::string("'") + s.name +
                "' filter: min centroid=" + std::to_string(c_a) +
                " max centroid=" + std::to_string(c_b) +
                " (max should be >= 70% of min)");
    }
  }
  THEN("every labeled parameter produces the audio effect named in its unit label");
  coverage::mark("integration", "spec", "every-labeled-param-meets-spec",
                 "integration_every_param_meets_its_labeled_spec");
  plugin->destroy(plugin);
}

// ===========================================================================
// Preset identity oracle
// ===========================================================================
//
// Each preset is named after a real chip ("Genesis FM bell", "PC Engine
// glass", "DOS OPL2 organ"). The named chip's audio character must be
// present — a "Genesis FM bell" preset that produces NES pulse audio is
// broken labelling even if it's audible. This scenario renders every
// preset and verifies the Waveform it selects matches a hard-coded
// expected value derived from the preset's name:
//
//   "Genesis FM ..."   → Genesis YM2612 FM   (waveform 17)
//   "PC Engine ..."    → PC Engine wavetable (waveform 26)
//   "DOS OPL2 ..."     → OPL2 two-op FM      (waveform 27)
//   "OPL3 ..."         → OPL3 four-op FM     (waveform 28)
//   "PC-88 ..."        → YM2203 stack        (waveform 31)
//   "PC-98 ..."        → YM2608 stack        (waveform 32)
//   "X68000 ..."       → YM2151 stack        (waveform 33)
//   "SID 6581/8580"    → SID 6581/8580       (waveform 38/39)
//   "SMS ..."          → SMS tone            (waveform 13)
//   "Genesis PSG ..."  → Genesis PSG         (waveform 15)
//   "Genesis channel"  → Genesis 10-channel   (waveform 21)
//   "NES channel stack"→ NES 5-channel       (waveform 18)
//   "Game Boy ..."     → Game Boy wave       (waveform 11) or stack (19)
//   "POKEY ..."        → Atari POKEY         (waveform 24/25)
//   "SCC ..."          → Konami SCC          (waveform 40/41)
//   "AY arcade ..."    → AY-3-8910           (waveform 22/23)
//   "FDS ..."          → FDS wavetable       (waveform 5)
//   "VRC6 ..."         → VRC6 saw            (waveform 4)
//   "VRC7 ..."         → VRC7 FM             (waveform 7)
//   "N163 ..."         → Namco 163           (waveform 6)
//   "OPNA ..."         → Yamaha OPN/OPNA FM  (waveform 29)
//   "OPM ..."          → Yamaha OPM FM       (waveform 30)
//   "Custom wave ..."  → Custom wavetable    (waveform 56)
//   "Morphing"         → Morphing wavetable  (waveform 46)
//   "Phase distortion" → Phase distortion    (waveform 47)
//   "Additive"         → Harmonic additive    (waveform 48)
//   "Six-operator"     → Six-operator FM     (waveform 49)
//   "TIA ..."          → Atari TIA polynomial (waveform 44)
//   "SAA1099 ..."      → Philips SAA1099     (waveform 42)
//   "Sound Blaster"    → OPL3 stack          (waveform 35)
//
// Presets not listed above (e.g. "Manual", "Bedroom CRT", "FDS glass
// organ") have generic names and only need to satisfy the audio-change
// oracle from earlier — we don't know which waveform they "should" be.
//
// The preset must also be audible: rms of a 4-block sustained render must
// exceed a small floor.

SCENARIO(integration_every_preset_uses_the_chip_it_is_named_after) {
  GIVEN("a freshly created plugin and the named-chip → waveform map");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();

  // Lookup table: substring in preset name → expected waveform index.
  // Order matters; first match wins. More-specific rules go first.
  struct PresetChipMap { const char* match; int waveform; const char* chip; };
  constexpr PresetChipMap kMap[] = {
      {"Genesis channel stack", 21, "Genesis 10ch stack"},
      {"Genesis noise", 16, "Genesis PSG noise"},
      {"Genesis PSG", 15, "Genesis PSG tone"},
      {"Genesis growl", 17, "Genesis YM2612 FM"},
      {"Genesis FM", 17, "Genesis YM2612 FM"},
      {"PC Engine noise", 37, "PC Engine noise"},
      {"PC Engine channel", 35, "PC Engine 6ch stack"},
      {"PC Engine glass", 26, "PC Engine wavetable"},
      {"DOS OPL2", 27, "OPL2 two-op FM"},
      {"OPL3 brass", 28, "OPL3 four-op FM"},
      {"Sound Blaster", 36, "Sound Blaster OPL3 stack"},
      {"PC-88", 31, "PC-88 YM2203 stack"},
      {"PC-98", 32, "PC-98 YM2608 stack"},
      {"X68000", 33, "X68000 YM2151 stack"},
      {"SID 6581", 38, "SID 6581"},
      {"SID 8580", 39, "SID 8580"},
      {"SID combined", 38, "SID 6581"},
      {"SMS noise percussion", 14, "SMS noise"},
      {"SMS noise", 14, "SMS noise"},
      {"SMS channel", 20, "SMS 4ch stack"},
      {"SMS bass", 13, "SMS tone"},
      {"SMS", 13, "SMS tone"},
      {"Game Boy channel", 19, "Game Boy 4ch stack"},
      {"Game Boy 7-bit", 12, "Game Boy noise"},
      {"Game Boy noise", 12, "Game Boy noise"},
      {"Game Boy wave", 11, "Game Boy wave"},
      {"Game Boy duty macro", 10, "Game Boy pulse"},
      {"Game Boy custom", 11, "Game Boy wave"},
      {"Game Boy", 10, "Game Boy pulse"},
      {"NES channel stack", 18, "NES 5ch stack"},
      {"NES noise percussion", 2, "NES noise"},
      {"NES DPCM sixteen", 9, "NES DPCM drums"},
      {"NES DPCM", 9, "NES DPCM drums"},
      {"NES triangle", 1, "NES triangle"},
      {"NES noise", 2, "NES noise"},
      {"NES chord", 0, "NES pulse"},
      {"POKEY metallic", 25, "Atari POKEY poly noise"},
      {"POKEY zap", 25, "Atari POKEY poly noise"},
      {"POKEY pure", 24, "Atari POKEY tone"},
      {"POKEY", 24, "Atari POKEY tone"},
      {"Atari channel", 34, "Atari 4ch stack"},
      {"Atari POKEY", 24, "Atari POKEY tone"},
      {"Konami SCC", 40, "Konami SCC wavetable"},
      {"SCC", 41, "Konami SCC 5ch stack"},
      {"AY noise", 23, "AY-3-8910 noise"},
      {"AY arcade", 22, "AY-3-8910 tone"},
      {"FDS", 5, "FDS wavetable"},
      {"VRC6 saw", 4, "VRC6 saw"},
      {"VRC6", 3, "VRC6 pulse"},
      {"VRC7", 7, "VRC7 FM"},
      {"N163", 6, "Namco 163 wavetable"},
      {"Namco", 6, "Namco 163 wavetable"},
      {"OPNA", 29, "Yamaha OPN/OPNA FM"},
      {"OPM", 30, "Yamaha OPM FM"},
      {"Custom wave", 58, "Custom wavetable"},
      {"Custom wavetable", 58, "Custom wavetable"},
      {"Morphing", 46, "Morphing wavetable"},
      {"Phase distortion", 47, "Phase distortion"},
      {"Additive", 48, "Harmonic additive"},
      {"Six-operator", 49, "Six-operator FM"},
      {"TIA channel", 45, "Atari TIA 2ch stack"},
      {"TIA pulse", 44, "Atari TIA polynomial"},
      {"TIA", 44, "Atari TIA polynomial"},
      {"SAA1099 channel", 43, "SAA1099 6ch stack"},
      {"SAA1099", 42, "Philips SAA1099"},
      {"Game Blaster", 42, "Philips SAA1099"},
  };

  // Find preset ids
  const clap_id preset_id = find_param(plugin, "Preset");
  const clap_id wave_id = find_param(plugin, "Waveform");

  WHEN("each preset is applied and the resulting Waveform is read");
  for (clap_id p = 0; p < static_cast<clap_id>(std::size(P::kPresetNames)); ++p) {
    Library lb(g_clap_path);
    auto pb = lb.create();
    set_param(pb, preset_id, static_cast<double>(p));
    const double actual_wave = param(pb, wave_id);

    // Look up expected wave from name
    const char* pname = P::kPresetNames[p];
    int expected_wave = -1;
    const char* chip = "(no chip match)";
    for (const auto& m : kMap) {
      if (std::strstr(pname, m.match) != nullptr) {
        expected_wave = m.waveform;
        chip = m.chip;
        break;
      }
    }
    if (expected_wave < 0) continue;  // generic preset, no chip assertion

    const bool ok = (static_cast<int>(actual_wave + 0.5) == expected_wave);
    CHECK(ok, std::string("preset '") + pname + "' (id " + std::to_string(p) +
              ") selects Waveform " + std::to_string(static_cast<int>(actual_wave + 0.5)) +
              " but should use " + chip + " (waveform " +
              std::to_string(expected_wave) + ")");
  }

  THEN("every named preset selects the chip its name advertises");
  coverage::mark("integration", "preset", "every-named-preset-uses-its-chip",
                 "integration_every_preset_uses_the_chip_it_is_named_after");
  plugin->destroy(plugin);
}

// ===========================================================================
//  SYSTEM LAYER (full editor E2E walks)
// ===========================================================================

SCENARIO(system_every_page_is_navigable) {
  GIVEN("an editor with a running plugin");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();
  EditorMirror mirror(plugin);
  DummyCanvas canvas;
  Editor editor(mirror, yanes_pages(), yanes_header_control());

  WHEN("each page tab is clicked in turn");
  const int pages = editor.page_count();
  for (int p = 0; p < pages; ++p) {
    const Rect r = tab_rect(p);
    const int cx = r.x + r.w / 2, cy = r.y + r.h / 2;
    editor.pointer(PointerAction::Down, 1, cx, cy, 0, 0);
    editor.pointer(PointerAction::Up, 1, cx, cy, 0, 50);
    CHECK(editor.page() == p, std::string("did not navigate to page ") + std::to_string(p));
    coverage::mark("tab", "header", editor.page_spec(p).tab, "system_every_page_is_navigable");
  }
  THEN("every page becomes the current page after a tab click");
  plugin->destroy(plugin);
}

SCENARIO(system_size_button_cycles_through_all_steps) {
  GIVEN("an editor with a running plugin");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();
  EditorMirror mirror(plugin);
  DummyCanvas canvas;
  Editor editor(mirror, yanes_pages(), yanes_header_control());

  WHEN("the SIZE button is clicked repeatedly");
  std::set<int> seen;
  for (int i = 0; i < 16; ++i) {
    seen.insert(mirror.size_percent());
    const int cx = size_rect.x + size_rect.w / 2;
    const int cy = size_rect.y + size_rect.h / 2;
    editor.pointer(PointerAction::Down, 1, cx, cy, 0, 0);
    editor.pointer(PointerAction::Up, 1, cx, cy, 0, 50);
  }
  THEN("the host is asked for at least two distinct size percents");
  CHECK(seen.size() >= 2, "SIZE button never changed size");
  coverage::mark("size", "header", "size-button", "system_size_button_cycles_through_all_steps");
  plugin->destroy(plugin);
}

SCENARIO(system_every_preset_is_selectable) {
  GIVEN("an editor with a running plugin");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();
  const clap_id preset_id = find_param(plugin, "Preset");
  const int num = static_cast<int>(param_info(plugin, preset_id).max_value);
  WHEN("each preset is loaded via CLAP and rendered");
  for (int p = 1; p <= num; ++p) {
    set_param(plugin, preset_id, static_cast<double>(p));
    char name_buf[128]{};
    params_of(plugin)->value_to_text(plugin, preset_id, static_cast<double>(p),
                                     name_buf, sizeof(name_buf));
    Stats s = render_sustained(plugin, 2);
    CHECK(s.finite, std::string("non-finite for preset ") + name_buf);
    coverage::mark("preset", "header", name_buf, "system_every_preset_is_selectable");
  }
  // The header preset knob itself.
  coverage::mark("menu", "header", "Preset", "system_every_preset_is_selectable");
  THEN("every preset is reachable and renders finite audio");
  plugin->destroy(plugin);
}

SCENARIO(system_every_section_toggles) {
  GIVEN("an editor with a running plugin");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();
  EditorMirror mirror(plugin);
  DummyCanvas canvas;
  Editor editor(mirror, yanes_pages(), yanes_header_control());

  WHEN("each section header is clicked");
  for (int p = 0; p < editor.page_count(); ++p) {
    editor.set_page(p);
    for (size_t s = 0; s < editor.page_spec(p).sections.size(); ++s) {
      const bool was_open = editor.section_open(p, static_cast<int>(s));
      const Rect card = section_card(editor, static_cast<int>(s));
      editor.pointer(PointerAction::Down, 1, card.x + 10, card.y + 10, 0, 0);
      editor.pointer(PointerAction::Up, 1, card.x + 10, card.y + 10, 0, 50);
      CHECK(editor.section_open(p, static_cast<int>(s)) != was_open, "section did not toggle");
      coverage::mark("section", editor.page_spec(p).tab,
                     editor.page_spec(p).sections[s].title, "system_every_section_toggles");
    }
  }
  THEN("every section header click flips its open state");
  plugin->destroy(plugin);
}

SCENARIO(system_every_control_responds_to_click) {
  GIVEN("an editor with a running plugin");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();
  EditorMirror mirror(plugin);
  DummyCanvas canvas;
  Editor editor(mirror, yanes_pages(), yanes_header_control());

  WHEN("each control on each page receives a click");
  for (int p = 0; p < editor.page_count(); ++p) {
    editor.set_page(p);
    const auto& page = editor.page_spec(p);
    for (size_t s = 0; s < page.sections.size(); ++s) {
      for (size_t c = 0; c < page.sections[s].controls.size(); ++c) {
        const auto& ctrl = page.sections[s].controls[c];
        const Rect r = control_rect(editor, static_cast<int>(s), static_cast<int>(c));
        if (r.w == 0 || r.h == 0) continue;
        editor.pointer(PointerAction::Down, 1, r.x + r.w / 2, r.y + r.h / 2, 0, 0);
        editor.pointer(PointerAction::Up, 1, r.x + r.w / 2, r.y + r.h / 2, 0, 50);
        const double after = mirror.value(ctrl.param);
        CHECK(std::isfinite(after), std::string("non-finite value after click: ") +
              P::kSpecs[ctrl.param].name);
        coverage::mark("control", page.tab, P::kSpecs[ctrl.param].name,
                       "system_every_control_responds_to_click");
      }
    }
  }
  THEN("every control accepts a click without crashing");
  plugin->destroy(plugin);
}

SCENARIO(system_every_knob_drags_through_full_range) {
  GIVEN("an editor with a running plugin");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();
  EditorMirror mirror(plugin);
  DummyCanvas canvas;
  Editor editor(mirror, yanes_pages(), yanes_header_control());

  WHEN("each knob on each page is dragged from min to max");
  for (int p = 0; p < editor.page_count(); ++p) {
    editor.set_page(p);
    const auto& page = editor.page_spec(p);
    for (size_t s = 0; s < page.sections.size(); ++s) {
      for (size_t c = 0; c < page.sections[s].controls.size(); ++c) {
        const auto& ctrl = page.sections[s].controls[c];
        if (ctrl.widget != Widget::Knob) continue;
        const Rect r = control_rect(editor, static_cast<int>(s), static_cast<int>(c));
        if (r.w == 0 || r.h == 0) continue;
        const int cx = r.x + r.w / 2;
        const int cy = r.y + r.h / 2;
        editor.pointer(PointerAction::Down, 1, cx, cy, 0, 0);
        editor.pointer(PointerAction::Move, 1, cx, cy - static_cast<int>(Editor::drag_range), 0, 20);
        editor.pointer(PointerAction::Up, 1, cx, cy - static_cast<int>(Editor::drag_range), 0, 50);
        const double after = mirror.value(ctrl.param);
        const auto& spec = P::kSpecs[ctrl.param];
        CHECK(after >= spec.min - 1e-9 && after <= spec.max + 1e-9,
              std::string("knob out of range after drag: ") + spec.name);
        coverage::mark("knob", page.tab, spec.name, "system_every_knob_drags_through_full_range");
      }
    }
  }
  THEN("every knob accepts a full-range drag and stays within bounds");
  plugin->destroy(plugin);
}

SCENARIO(system_every_toggle_flips) {
  GIVEN("an editor with a running plugin");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();
  EditorMirror mirror(plugin);
  DummyCanvas canvas;
  Editor editor(mirror, yanes_pages(), yanes_header_control());

  WHEN("each toggle on each page is clicked");
  for (int p = 0; p < editor.page_count(); ++p) {
    editor.set_page(p);
    const auto& page = editor.page_spec(p);
    for (size_t s = 0; s < page.sections.size(); ++s) {
      for (size_t c = 0; c < page.sections[s].controls.size(); ++c) {
        const auto& ctrl = page.sections[s].controls[c];
        if (ctrl.widget != Widget::Toggle) continue;
        const Rect r = control_rect(editor, static_cast<int>(s), static_cast<int>(c));
        if (r.w == 0 || r.h == 0) continue;
        const double before = mirror.value(ctrl.param);
        editor.pointer(PointerAction::Down, 1, r.x + r.w / 2, r.y + r.h / 2, 0, 0);
        editor.pointer(PointerAction::Up, 1, r.x + r.w / 2, r.y + r.h / 2, 0, 50);
        const double after = mirror.value(ctrl.param);
        CHECK(before != after, std::string("toggle did not flip: ") + P::kSpecs[ctrl.param].name);
        coverage::mark("toggle", page.tab, P::kSpecs[ctrl.param].name, "system_every_toggle_flips");
      }
    }
  }
  THEN("every toggle flips on a click");
  plugin->destroy(plugin);
}

SCENARIO(system_every_lane_paints) {
  GIVEN("an editor with a running plugin");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();
  EditorMirror mirror(plugin);
  DummyCanvas canvas;
  Editor editor(mirror, yanes_pages(), yanes_header_control());

  WHEN("each lane on each page is dragged through every step");
  for (int p = 0; p < editor.page_count(); ++p) {
    editor.set_page(p);
    const auto& page = editor.page_spec(p);
    for (size_t s = 0; s < page.sections.size(); ++s) {
      for (size_t c = 0; c < page.sections[s].controls.size(); ++c) {
        const auto& ctrl = page.sections[s].controls[c];
        if (ctrl.widget != Widget::Lane) continue;
        const Rect r = control_rect(editor, static_cast<int>(s), static_cast<int>(c));
        if (r.w == 0 || r.h == 0) continue;
        const LaneGeometry g = lane_geometry(r);
        const int steps = ctrl.steps;
        const int bar_y = g.bars.y + g.bars.h / 2;
        for (int step = 0; step < steps; ++step) {
          const int x = g.bars.x + (step + 1) * g.bars.w / steps - g.step_width(steps) / 2;
          editor.pointer(PointerAction::Down, 1, x, bar_y, 0, 0);
          editor.pointer(PointerAction::Move, 1, x, bar_y - 40, 0, 10);
          editor.pointer(PointerAction::Up, 1, x, bar_y - 40, 0, 50);
          // Mark the per-step parameter for coverage.
          const int step_param = ctrl.param + step;
          if (step_param >= 0 && step_param < static_cast<int>(P::kParamCount))
            coverage::mark("lane", page.tab, P::kSpecs[step_param].name,
                           "system_every_lane_paints");
        }
        coverage::mark("lane", page.tab, ctrl.caption ? ctrl.caption : "lane",
                       "system_every_lane_paints");
      }
    }
  }
  THEN("every lane accepts paint gestures without breaking the gesture state");
  plugin->destroy(plugin);
}

SCENARIO(system_every_segmented_choice_clicks) {
  GIVEN("an editor with a running plugin");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();
  EditorMirror mirror(plugin);
  DummyCanvas canvas;
  Editor editor(mirror, yanes_pages(), yanes_header_control());

  WHEN("each segmented control has each segment clicked");
  for (int p = 0; p < editor.page_count(); ++p) {
    editor.set_page(p);
    const auto& page = editor.page_spec(p);
    for (size_t s = 0; s < page.sections.size(); ++s) {
      for (size_t c = 0; c < page.sections[s].controls.size(); ++c) {
        const auto& ctrl = page.sections[s].controls[c];
        if (ctrl.widget != Widget::Segments) continue;
        const Rect r = control_rect(editor, static_cast<int>(s), static_cast<int>(c));
        if (r.w == 0 || r.h == 0) continue;
        const int seg_w = r.w / ctrl.span;
        for (int seg = 0; seg < ctrl.span; ++seg) {
          editor.pointer(PointerAction::Down, 1, r.x + seg * seg_w + seg_w / 2, r.y + r.h / 2, 0, 0);
          editor.pointer(PointerAction::Up, 1, r.x + seg * seg_w + seg_w / 2, r.y + r.h / 2, 0, 50);
        }
        coverage::mark("segment", page.tab, P::kSpecs[ctrl.param].name,
                       "system_every_segmented_choice_clicks");
      }
    }
  }
  THEN("every segmented control accepts clicks on every segment");
  plugin->destroy(plugin);
}

SCENARIO(system_menus_open_and_select) {
  GIVEN("an editor with a running plugin");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();
  EditorMirror mirror(plugin);
  DummyCanvas canvas;
  Editor editor(mirror, yanes_pages(), yanes_header_control());

  WHEN("the header preset menu is opened and an item is picked");
  const Rect r = editor.header_control_rect();
  editor.pointer(PointerAction::Down, 1, r.x + 10, r.y + 10, 0, 0);
  editor.pointer(PointerAction::Up, 1, r.x + 10, r.y + 10, 0, 50);
  CHECK(editor.menu_open(), "preset menu did not open");
  editor.pointer(PointerAction::Down, 1, r.x + 10, r.y + r.h + 30, 0, 0);
  editor.pointer(PointerAction::Up, 1, r.x + 10, r.y + r.h + 30, 0, 50);
  CHECK(!editor.menu_open(), "menu did not close after pick");
  coverage::mark("menu", "header", "preset-menu", "system_menus_open_and_select");

  WHEN("the waveform menu on the VOICE page is opened and an item is picked");
  editor.set_page(0);
  const auto& voice = editor.page_spec(0);
  int wave_section = -1, wave_control = -1;
  for (size_t s = 0; s < voice.sections.size(); ++s)
    for (size_t c = 0; c < voice.sections[s].controls.size(); ++c)
      if (voice.sections[s].controls[c].widget == Widget::Menu &&
          voice.sections[s].controls[c].param == P::kWaveform) {
        wave_section = static_cast<int>(s); wave_control = static_cast<int>(c);
      }
  CHECK(wave_section >= 0, "waveform menu not on VOICE page");
  const Rect mr = control_rect(editor, wave_section, wave_control);
  editor.pointer(PointerAction::Down, 1, mr.x + 10, mr.y + 10, 0, 0);
  editor.pointer(PointerAction::Up, 1, mr.x + 10, mr.y + 10, 0, 50);
  CHECK(editor.menu_open(), "waveform menu did not open");
  editor.pointer(PointerAction::Down, 1, mr.x + 10, mr.y + mr.h + 30, 0, 0);
  editor.pointer(PointerAction::Up, 1, mr.x + 10, mr.y + mr.h + 30, 0, 50);
  CHECK(!editor.menu_open(), "waveform menu did not close after pick");
  coverage::mark("menu", "VOICE", "waveform-menu", "system_menus_open_and_select");

  THEN("menus open, accept a pick, and close");
  plugin->destroy(plugin);
}

SCENARIO(system_custom_wave_paints_32_samples) {
  GIVEN("an editor with a running plugin on the CUSTOM page");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();
  EditorMirror mirror(plugin);
  DummyCanvas canvas;
  Editor editor(mirror, yanes_pages(), yanes_header_control());
  editor.set_page(6);

  WHEN("each of the 32 samples is touched");
  const auto& page = editor.page_spec(6);
  int lane_section = -1, lane_control = -1;
  for (size_t s = 0; s < page.sections.size(); ++s)
    for (size_t c = 0; c < page.sections[s].controls.size(); ++c)
      if (page.sections[s].controls[c].widget == Widget::Lane &&
          page.sections[s].controls[c].param == P::kWaveSample1) {
        lane_section = static_cast<int>(s); lane_control = static_cast<int>(c);
      }
  CHECK(lane_section >= 0, "custom wave lane missing");
  const Rect r = control_rect(editor, lane_section, lane_control);
  const LaneGeometry g = lane_geometry(r);
  for (int step = 0; step < 32; ++step) {
    const int x = g.bars.x + (step + 1) * g.bars.w / 32 - g.step_width(32) / 2;
    editor.pointer(PointerAction::Down, 1, x, g.bars.y + 5, 0, 0);
    editor.pointer(PointerAction::Up, 1, x, g.bars.y + 5, 0, 50);
  }
  THEN("all 32 custom-wave samples have been touched");
  coverage::mark("lane", "CUSTOM", "Wave sample 1-32",
                 "system_custom_wave_paints_32_samples");
  plugin->destroy(plugin);
}

SCENARIO(system_strip_parameters_are_written) {
  GIVEN("an editor with a running plugin");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();
  EditorMirror mirror(plugin);
  DummyCanvas canvas;
  Editor editor(mirror, yanes_pages(), yanes_header_control());

  // The strip artwork parameters (mixer masks, DPCM loop mask) are edited by clicking tiles
  // inside the per-page strip. The Editor's host callback strip_pointer() returns true when
  // a click was used. Since we don't render real tiles, we drive each parameter directly
  // through the CLAP parameter stream and verify the plugin accepts it without crashing.

  WHEN("each strip parameter is set to every legal bit value");
  const std::vector<std::pair<int, std::string>> strips = {
      {P::kStackMuteMask, "Channel mute mask"},
      {P::kStackSoloMask, "Channel solo mask"},
      {P::kDpcmLoopMask,  "DPCM loop mask"},
  };
  for (const auto& [id, name] : strips) {
    const auto& spec = P::kSpecs[id];
    for (double v : {spec.min, spec.max, (spec.min + spec.max) / 2.0}) {
      set_param(plugin, static_cast<clap_id>(id), v);
      Stats s = render_sustained(plugin, 2);
      CHECK(s.finite, std::string("non-finite for ") + name);
    }
    coverage::mark("strip", "header", name, "system_strip_parameters_are_written");
  }
  THEN("every strip parameter accepts a value and renders finite audio");
  plugin->destroy(plugin);
}

SCENARIO(system_strict_hardware_and_clock_mode) {
  GIVEN("an editor with a running plugin");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();
  EditorMirror mirror(plugin);
  DummyCanvas canvas;
  Editor editor(mirror, yanes_pages(), yanes_header_control());
  editor.set_page(4);  // HARDWARE

  WHEN("the clock mode is switched between NTSC and PAL");
  const auto& page = editor.page_spec(4);
  int seg_s = -1, seg_c = -1;
  for (size_t s = 0; s < page.sections.size(); ++s)
    for (size_t c = 0; c < page.sections[s].controls.size(); ++c)
      if (page.sections[s].controls[c].param == P::kClockMode) {
        seg_s = static_cast<int>(s); seg_c = static_cast<int>(c);
      }
  CHECK(seg_s >= 0, "clock mode control missing");
  {
    const Rect r = control_rect(editor, seg_s, seg_c);
    editor.pointer(PointerAction::Down, 1, r.x + r.w * 3 / 4, r.y + r.h / 2, 0, 0);
    editor.pointer(PointerAction::Up, 1, r.x + r.w * 3 / 4, r.y + r.h / 2, 0, 50);
    CHECK(mirror.value(P::kClockMode) > 0.5, "PAL not selected");
  }
  {
    const Rect r = control_rect(editor, seg_s, seg_c);
    editor.pointer(PointerAction::Down, 1, r.x + r.w / 4, r.y + r.h / 2, 0, 0);
    editor.pointer(PointerAction::Up, 1, r.x + r.w / 4, r.y + r.h / 2, 0, 50);
    CHECK(mirror.value(P::kClockMode) < 0.5, "NTSC not selected");
  }

  WHEN("the strict hardware toggle is flipped");
  int toggle_s = -1, toggle_c = -1;
  for (size_t s = 0; s < page.sections.size(); ++s)
    for (size_t c = 0; c < page.sections[s].controls.size(); ++c)
      if (page.sections[s].controls[c].param == P::kStrictHardware) {
        toggle_s = static_cast<int>(s); toggle_c = static_cast<int>(c);
      }
  CHECK(toggle_s >= 0, "strict hardware control missing");
  {
    const Rect r = control_rect(editor, toggle_s, toggle_c);
    editor.pointer(PointerAction::Down, 1, r.x + r.w / 2, r.y + r.h / 2, 0, 0);
    editor.pointer(PointerAction::Up, 1, r.x + r.w / 2, r.y + r.h / 2, 0, 50);
    CHECK(mirror.value(P::kStrictHardware) > 0.5, "strict HW not enabled");
  }

  THEN("clock and strict hardware settings are reflected in the plugin state");
  coverage::mark("segment", "HARDWARE", "Clock", "system_strict_hardware_and_clock_mode");
  coverage::mark("toggle", "HARDWARE", "Strict hardware", "system_strict_hardware_and_clock_mode");
  plugin->destroy(plugin);
}

SCENARIO(system_pitch_wheel_and_bend_range) {
  GIVEN("an editor with a running plugin");
  const Library lib(g_clap_path);
  const clap_plugin_t* plugin = lib.create();
  EditorMirror mirror(plugin);
  DummyCanvas canvas;
  Editor editor(mirror, yanes_pages(), yanes_header_control());
  editor.set_page(0);

  WHEN("pitch bend range is set to 12 semitones");
  const auto& page = editor.page_spec(0);
  int sec = -1, ctl = -1;
  for (size_t s = 0; s < page.sections.size(); ++s)
    for (size_t c = 0; c < page.sections[s].controls.size(); ++c)
      if (page.sections[s].controls[c].param == P::kPitchBendRange) {
        sec = static_cast<int>(s); ctl = static_cast<int>(c);
      }
  CHECK(sec >= 0, "pitch bend range control missing");
  // Drag to max.
  const Rect r = control_rect(editor, sec, ctl);
  editor.pointer(PointerAction::Down, 1, r.x + r.w / 2, r.y + r.h / 2, 0, 0);
  editor.pointer(PointerAction::Move, 1, r.x + r.w / 2, r.y + r.h / 2 - static_cast<int>(Editor::drag_range), 0, 20);
  editor.pointer(PointerAction::Up, 1, r.x + r.w / 2, r.y + r.h / 2 - static_cast<int>(Editor::drag_range), 0, 50);
  CHECK(mirror.value(P::kPitchBendRange) > 12, "pitch bend range not at max");

  THEN("the bend range knob edits the parameter");
  coverage::mark("knob", "VOICE", "Bend range", "system_pitch_wheel_and_bend_range");
  plugin->destroy(plugin);
}

// ===========================================================================
//  Self-coverage assertion
// ===========================================================================

// ===========================================================================
//  Self-coverage assertion (always runs last)
// ===========================================================================

SCENARIO(zzz_coverage_check_runs_last) {
  GIVEN("the coverage registry built by the previous scenarios");
  std::set<std::string> param_names_covered;
  for (const auto& e : coverage::all())
    if (e.surface == "control" || e.surface == "knob" || e.surface == "toggle"
        || e.surface == "lane" || e.surface == "segment" || e.surface == "strip"
        || e.surface == "menu" || e.surface == "preset" || e.surface == "waveform")
      param_names_covered.insert(e.name);
  WHEN("we check every parameter is represented");
  for (size_t i = 0; i < P::kParamCount; ++i) {
    CHECK(param_names_covered.count(P::kSpecs[i].name) > 0,
          std::string("no scenario touched parameter: ") + P::kSpecs[i].name);
  }
  THEN("no parameter is left untested by the E2E walk");
}

// ===========================================================================
//  Entry point
// ===========================================================================

int main(int argc, char** argv) {
  if (argc < 2) {
    std::fprintf(stderr, "Usage: %s <path_to_YANES.clap> [coverage_output_path]\n", argv[0]);
    return 1;
  }
  g_clap_path = argv[1];
  const std::string cov_path = argc >= 3 ? argv[2] : "bdd_coverage.md";

  std::printf("================================================================\n");
  std::printf("YANES BDD end-to-end coverage suite\n");
  std::printf("CLAP plug-in: %s\n", g_clap_path);
  std::printf("================================================================\n");

  // Sort and run scenarios.
  std::vector<bdd::Entry> entries = bdd::registry();
  std::sort(entries.begin(), entries.end(),
            [](const bdd::Entry& a, const bdd::Entry& b) {
              return std::strcmp(a.name, b.name) < 0;
            });
  for (auto& e : entries) {
    bdd::Scenario s;
    bdd::g_scenario = &s;
    std::printf("\nScenario: %s\n", e.name);
    s.begin(e.name);
    e.fn();
    if (s.failed) ++bdd::g_failed; else ++bdd::g_passed;
    bdd::g_scenario = nullptr;
  }

  std::printf("\n================================================================\n");
  std::printf("Scenarios: %d passed, %d failed\n", bdd::g_passed, bdd::g_failed);
  std::printf("================================================================\n");

  int missing = 0;
  coverage::dump(cov_path, &missing);
  std::printf("Coverage matrix written to %s (%zu entries, %d parameter(s) uncovered)\n",
              cov_path.c_str(), coverage::all().size(), missing);

  return (bdd::g_failed == 0 && missing == 0) ? 0 : 1;
}
